networks:
  dae_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.29.0.0/16
# custom network with static ips
  

services:
  db:
    platform: linux/amd64
    image: postgis/postgis:16-3.5
    container_name: lbs_db
    environment:
      POSTGRES_DB: ${DB_NAME:-dae_db}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=C"
    volumes:
      - db_data:/var/lib/postgresql/data
      # keeps data after restarts
    networks:
      dae_net:
        ipv4_address: 172.29.0.2
        # static ip
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5
      # wait for db to start
    restart: unless-stopped

  web:
    build:
      context: .
      dockerfile: Dockerfile
      # build from dockerfile
    container_name: lbs_web

    env_file:
      - .env

    environment:
      DB_HOST: db

    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    networks:
      dae_net:
        ipv4_address: 172.29.0.3
    expose:
      - "8000"
    depends_on:
      db:
        condition: service_healthy
#    healthcheck:
#      test: ["CMD", "curl", "-f", "http://localhost:8000/" ]
#      interval: 30s
#      timeout: 10s
#      retries: 3
#      start_period: 60s
    restart: unless-stopped
    command: >
      sh -c "python manage.py migrate &&
             python manage.py loaddata geo/fixtures/dcc_admin_areas.json &&
             python manage.py loaddata geo/fixtures/amenities_dublin.json &&
             python manage.py loaddata geo/fixtures/routes_sample.json &&
             python manage.py import_osm_amenities &&
             python manage.py collectstatic --noinput --clear &&
             gunicorn --bind 0.0.0.0:8000 --workers 4 --worker-class sync --timeout 60 --forwarded-allow-ips='*' --access-logfile - --error-logfile - lbs.wsgi:application"

  nginx:
    platform: linux/amd64
    image: nginx:latest
    container_name: lbs_nginx
    volumes:
      - ./deploy/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - static_volume:/app/staticfiles:ro
    networks:
      dae_net:
        ipv4_address: 172.29.0.4
    ports:
      - "8080:80"
    depends_on:
      - web
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "80"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:8.6
    container_name: lbs_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-admin@example.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-admin}
      PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION: "False"
      PGADMIN_CONFIG_COOKIE_DEFAULT_SECURE: "False"
      PGADMIN_CONFIG_COOKIE_SAMESITE: "'Lax'"
      PGADMIN_CONFIG_PROXY_X_FOR_COUNT: 1
      PGADMIN_CONFIG_PROXY_X_PROTO_COUNT: 1
      PGADMIN_CONFIG_PROXY_X_HOST_COUNT: 1
      PGADMIN_CONFIG_SERVER_MODE: "False"
    networks:
      dae_net:
        ipv4_address: 172.29.0.5
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

volumes:
  db_data:
    driver: local
  static_volume:
    driver: local
  pgadmin_data:
    driver: local
